// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4yXOdGjoUk9DSz2TFwgWuKxIbS0v09bY',
    appId: '1:493617802271:web:7c8cd78eb2918500fb792a',
    messagingSenderId: '493617802271',
    projectId: 'timeless-love-54039',
    authDomain: 'timeless-love-54039.firebaseapp.com',
    storageBucket: 'timeless-love-54039.appspot.com',
    measurementId: 'G-GFX138WRFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP3e9CLZ9Q7cZh0L0yzAjG-OxNe6Hm7lo',
    appId: '1:493617802271:android:49b04b909ff45321fb792a',
    messagingSenderId: '493617802271',
    projectId: 'timeless-love-54039',
    storageBucket: 'timeless-love-54039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDzKSRtQocbiFMOnxYxecCifF3D_3xtww',
    appId: '1:493617802271:ios:4402b8692ee6dd81fb792a',
    messagingSenderId: '493617802271',
    projectId: 'timeless-love-54039',
    storageBucket: 'timeless-love-54039.appspot.com',
    iosClientId: '493617802271-j7suj3qfhmmef6iik3lulp8hq4tb18u7.apps.googleusercontent.com',
    iosBundleId: 'com.midouz.timelessLoveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDzKSRtQocbiFMOnxYxecCifF3D_3xtww',
    appId: '1:493617802271:ios:4402b8692ee6dd81fb792a',
    messagingSenderId: '493617802271',
    projectId: 'timeless-love-54039',
    storageBucket: 'timeless-love-54039.appspot.com',
    iosClientId: '493617802271-j7suj3qfhmmef6iik3lulp8hq4tb18u7.apps.googleusercontent.com',
    iosBundleId: 'com.midouz.timelessLoveApp',
  );
}
